document.writeln("<div class=\'srollx\'>");
document.writeln("    <div class=\'main\' deep=\'1\'>");
document.writeln("        <h2>床上~夫妻“性”性活...(未满18岁勿入)</h2><br data-filtered=\'filtered\'>");
document.writeln("        <hr>");
document.writeln("        <div class=\'title\'>男人有问题，女人黯然神伤</div>");
document.writeln("        <p>“老公嫌我下面松弛，我偷偷出了一次轨，人家说我夹得很紧，原来是他下面太细了，硬起来的时候跟棒棒冰差不多粗！”</p><br data-filtered=\'filtered\'>");
document.writeln("        <p>“跟他履行夫妻义务的时候，要跟他口很久，还是硬不起来，哎！”</p><br data-filtered=\'filtered\'>");
document.writeln("        <p>“每次我还没感觉呢，老公就一泻千里，还问我舒不舒服？无语”</p><br data-filtered=\'filtered\'>");
document.writeln("        <p>“没有性生活的婚姻，像守活寡，不知道还能坚持多久？”</p><br data-filtered=\'filtered\'>");
document.writeln("        <div class=\'title\'>少妇真人口述</div>");
document.writeln("        <div>");
document.writeln("            <img class=\'lazy\' src=\'./images/top1.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("            <div class=\'pt\'><span style=\'font-weight: bold;color:red;\'>张小姐口述：</span> 我才结婚两年，还没体验一次姐妹们说的高潮是什么！老公下面老不听指挥，动作一大，不经允许就流出来了，我还根本没感觉呢！太难熬了，真想找人“一夜情”放纵一下！自从用了董奉堂老医师的壮阳古方后，才两星期，老公一下子变得热血彭湃，连连激情也不休战，而且下面变魔术地长大，也变粗了，强劲有力，每次都能坚持30分钟左右，我都吃不消了！现在我啥都听老公的，太棒了！</div>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <img class=\'lazy\' src=\'./images/ttt1.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("            <div class=\'neirong\'>两个月后的一天，我在看电视，他刚洗完澡，因为用了董奉堂老医师的壮阳古方，下面胀得很大，突然把我按倒在沙发上，那略带胡茬的嘴在我的身上吻着，一个翻身骑到我的身上，支开我的双腿一个挺身，粗野的扯下我的内裤毫不客气的将进入了我。我心里一惊，这还是他么？粗了这么多？“疼”，我不自觉的叫出声了。老公并不理会我，继续着他的动作，我慢慢地放松了，从脚趾尖开始，觉得有一丝丝的暖意，然后顺着筋络，一直延伸到大腿根，紧接着，私处内不停的抽搐，大脑放空，觉得一瞬间欲仙欲死，不时有阵阵骚痒从大腿那儿往上延伸，沙发湿了一大片。</div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("        <div class=\'contact\'>");
document.writeln("		&nbsp;");
document.writeln("		</div>");
document.writeln("");
document.writeln("");
document.writeln("        <div>");
document.writeln("            <img class=\'lazy\' src=\'./images/aa1.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("            <div class=\'pt\'><span style=\'font-weight: bold;color:red;\'>刘女士口述：</span>我老公以前还行，勉强能有10分钟左右，可这几年时间越来越不行了，勃起的时候也不像过去那么硬，总觉得软软的，有时候放都放不进去，现在我们房事基本上没有高潮过。我们很少亲热，觉生活特没劲儿，每天晚上都不想回家！</div>");
document.writeln("            <div class=\'neirong\'>一次跟闺蜜聊天说起他老公，和我老公的情况一样，后来经过朋友介绍使用了董奉堂老医师的壮阳古方，一个月已经重振了男人雄风，我马上叫我老公联系了董奉堂老医师，董奉堂老医师给我老公问诊后，针对我老公的身体情况开方配药，服用3天后就开始有反应了，大大提高了他的兴致，以前感觉都有点性冷淡，可能不自信吧，现在不一样了，服用了一周后，他竟然有了晨勃，这是这些年第一次有，还没等我反应过来，我就被他压在了身下，那是种多少年都没试过的酸爽，每一根神经都在跳动！他下面硬硬的，我的血液流淌得很快，心脏都调到了嗓子眼，我像第一次一样任由她摆布，每一次撞击都让我全身一震，浑身酥麻酥麻的，随之他的速度越来越快，我紧紧地抱着他大叫起来，第一次体会到了那种水乳交融的感觉。</div>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <img class=\'lazy\' src=\'./images/top2.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("            <div class=\'pt\'><span style=\'font-weight: bold;color:red;\'>赵女士口述：</span>我老公晚上从不碰我，几个月都不做一次，一开始我怀疑他在外面有了小三，我变得焦虑多疑，在几次大吵大闹后，发现不是我们的感情出了问题，而是他的身体出了问题，去医院检查得知是前列腺问题导致的性功能低下。这两年来，断断续续一直在治疗却没有半点效果。有时候我俩都来感觉了，身体饥渴难耐，可是他在上面没两三下就结束了，我眼巴巴地看着他急到满头大汗却无能为力。他也变得越来越不自信，你说长期都这样哪个女人受得了？每次身体难受的时候，我都想象跟其他男人做爱的情景。很多人说我骚，前段时间我差点出轨了，跟他的一个合作伙伴，但是还是悬崖勒马了，没有冲破道德底线，如果这样下去，我真的不敢保证我们的婚姻还能维持多久。</div>");
document.writeln("            <div class=\'neirong\'>自从使用了董奉堂老医师的壮阳古方后，他晚上小便的次数明显减少了，睡觉不出虚汗了，一个周期没使用完，有一天晚上他说下面胀胀的，很想要，那天晚上不知是不是心理作用，老公那里明显变硬了、变挺了，抽插的速度也越来越快，我全身酥麻，很快高潮了，可老公还没有想射的意思，老公在一次加快插抽的频率，我下面被塞得满满的、涨涨的，每一次撞击都让我全身一震，禁不住的大叫了出来，老公的速度更快了，终于在一阵更加紧密有力的冲撞后，感到一股一股的热流冲进我的身体深处，我全身瘫软，真是酣畅淋漓。</div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("");
document.writeln("      <div class=\'contact\'>");
document.writeln("	  &nbsp;");
document.writeln("	  </div>");
document.writeln("");
document.writeln("");
document.writeln("        <div class=\'title\'>董奉堂老强肾古方的历史渊源——清宫秘传</div>");
document.writeln("        <div style=\'text-align: center;\'>");
document.writeln("            <img class=\'lazy\' src=\'./images/top3.jpg\' width=\'50%\' alt=\'\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'neirong\'>众所周知同治帝喜欢寻花问柳，虽说最后死于天花，但在那个时候一夜御九妃不是传闻。如果不是喜欢流连于妓院染上病毒，他在床上的造诣会比他当皇帝更有成就感。</div>");
document.writeln("        <div>");
document.writeln("     ");
document.writeln("            <img class=\'lazy\' src=\'./images/11.png\' width=\'100%\' alt=\'\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'neirong\'>皇家图书馆里收藏着各种版本的房中术和描绘这些房中术的《春宫图》，以此教导成年皇帝，如何采阴壮阳，享受快乐的性生活，广延帝嗣。这类的春宫书籍，堆积在文渊阁等各大小皇家书库之中，包括《房中术》、《秘戏图》、《肉蒲团》、《玉房秘诀》、《养生秘解》等。这些书中，记载了各种御女的成功范例，最有代表性的就是黄帝，传说他一生之中，同1200个女人交合，最后练就了金刚之身，阴阳双盛，气血丰盈，长生不老。同治皇帝被这些记载和夸张的春宫图所吸引，每天沉缅其中，如醉如痴。同治皇帝本来就早熟，他和堂弟一起，仿效着玉女教导黄帝的九种功法，临御女人：龙翻、虎步、猿搏、蚕附、龟腾、凤翔、兔吮毫、鱼唼鳞、鹤交颈。</div>");
document.writeln("        <div class=\'neirong\'>在清宫秘案中就有记载，当年同治帝房事过度，偶有不举，曾得一位满族姓董奉堂的御医，可奏壮阳益火、补肾固精、理气安神之效，独家秘方使皇帝精力充沛，性欲大增，房事更是持久和谐。言“董奉堂老强肾古方”，可治筋骨乏力、头晕眼花、盗汗、遗精、阳痿等症。既壮先天又补后天，既补元气又补中气，其妙不能尽述也。”</div>");
document.writeln("        <div class=\'title\'>皇家御医传承人</div>");
document.writeln("        <div>");
document.writeln("            <img class=\'lazy\' src=\'./images/top5.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'pt\'><span style=\'color:red;font-weight: bold;\'>董奉堂老中医</span>，是长白山满族传统医药非遗传承人，也是满医第十三代传人。祖辈更是当时皇家御医。为了捍卫“原版中医”传承中医药学术思想，首度公开了清宫御用奇方，董奉堂老医师，不求名，不为利，只为帮助男人告别阳痿、早泄、短小、腰膝酸软、尿频尿急等男性问题，重振男人雄风。</div>");
document.writeln("        ");
document.writeln("");
document.writeln("");
document.writeln("       <div class=\'contact\'>	  ");
document.writeln("	   &nbsp;");
document.writeln("	   </div>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("        <div class=\'title\'>董奉堂老强肾古方，渗透每一个细胞让你做回真正的男人</div>");
document.writeln("        <div class=\'neirong\'>肾是男人的命根子，肾也是女人健康美丽的总管家，控制着身体的内分泌，所以说，无论是男人还是女人，肾是人的先天之本！男人30岁之后，肾开始老化，而且阳痿早泄的情况也出现了，大部分男性朋友采用的调理方法都不科学，阳痿了，就吃伟哥，或者是小店里买的各种三无产品和激素，殊不知，这些都不能根除，而且长期使用对身体副作用都很大，千万别让这些激素把你的身体“掏空”，男人要想壮阳延时，补肾养气才是根本之道！</div>");
document.writeln("        <div class=\'neirong\'>肾出问题了，从根源滋补肾，修复肾，才能真正解决问题，内调方能外养，肾健康了不光是延时壮阳好，人也会变的有精神！千万别急于求成走到误区：</div>");
document.writeln("        <div>");
document.writeln("            <strong><span style=\'color:red;\'>误区1：</span>吃伟哥：破坏人体细胞，长期服用还会对胃、脏器都有一定的损害。时间久了极易产生依赖性，甚至还会得骨质疏松。</strong><br data-filtered=\'filtered\'><br data-filtered=\'filtered\'>");
document.writeln("            <strong><span style=\'color:red;\'>误区2：</span>吃保健品就能补肾壮阳：市场上的保健品基本都是炒作用的，基本上是没有什么功效，如果真有功效，国家为什么不给他批一个国药准字的批号，而是只给一个保健食品的批号，大家细想一下就明白了。</strong><br data-filtered=\'filtered\'><br data-filtered=\'filtered\'>");
document.writeln("            <strong><span style=\'color:red;\'>误区3：</span>吃人参，锁阳，肉苁蓉等就能壮阳：民间一直都认为这些补品有很强大的补气补肾功效，其实不然。对于气血亏空的人来说，身体虚弱，无法全面吸收这些营养，导致虚不受补。而且血液匮乏跟不上气的运行，反而让人更加虚弱！</strong>");
document.writeln("        </div>");
document.writeln("        <p style=\'font-size: 20px;margin: 20px 0;color: red;font-weight: bold;text-align: center;text-decoration: underline;\'>在这里也告诫大家千万不要随便乱服药物或者去做手术！</p>");
document.writeln("        <div class=\'pt\'>董奉堂老医师是当代唯一满医传承人。早年毕业于延边大学，从小继承满医祖传医技，师承关东萨满名师，处于对传统医学的酷爱和古代中医房中术技法的追求，中年后求学于长春中医药大学，中医本科、职业医师，多年来游学遍访，取其精华，积累了丰富的民间医药知识和经验，并经过世代传承，形成了一套别具特色且行之有效的满族医药学说——如膏药外敷法、喷吹法、针灸疗法、泻血拔罐法、药酒疗法、避瘟疗法、热敷法、冰敷法、雪疗法、正骨疗法、食物疗法、温泉洗浴疗法等。 </div>");
document.writeln("        <div class=\'pt\'>这些疗法内容丰富，行之有效，其中董奉堂老强肾古方在满族聚居地区或北方民间仍然保留着并为人们所喜用。</div>");
document.writeln("        <img class=\'lazy\' src=\'./images/tt1.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        <p style=\'text-align: center;font-size: 15px;\'>董奉堂老医师也非常擅长熬制膏滋</p>");
document.writeln("        <div class=\'pt\'>现在很多人都以为外国的东西好，什么美国、非洲，印第安的，这些东西只能坚持一时，来的快去得也快，用一次把身体掏空一次，越用越不行，力量、时间、硬度全都大不如从前。我这个方子是从大清朝皇宫里传下来的，补肾养睾不伤肾，壮阳不上火，除了夫妻性生活增强，还能改善腰酸背痛、尿频尿急，前列腺炎、畏寒、易出汗、倦态等等……现在我把它拿出来，不为名，我早些年已经受到国家领导的接见了，还要什么名？也不为钱，每年政府给我补贴够花了，要那么多钱干嘛？现在我就希望能帮助到更多的人。</div>");
document.writeln("      ");
document.writeln("        <img class=\'lazy\' src=\'./images/top8.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        <div class=\'pt\'>其药是原生态疗法，均来自古老的民间，尤其以名贵药材为主，应时而采，骨法炮制，除杂、清洗、晾晒、切片、烘、蜜制、酒制、醋制等工序，有的甚至达到近百道工序，因人而异，单独制药，对症治疗，效果显著。</div>");
document.writeln("        <img class=\'lazy\' src=\'./images/top7.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        <div class=\'pt\'>满医文化是散落民间的智慧，董奉堂老医师的心愿就是将满族医药无私奉献，发扬光大，传承下去，让这古老的智慧重新在民间闪光延续。</div>");
document.writeln("");
document.writeln("        <div style=\'padding: 10px;text-align: justify;border: 3px solid rgb(178,0,0);\'>捍卫“原版中医”传承中医药学术思想，首度公开了清宫御用奇方，董奉堂老医师不求名，不为利，只为帮助男人告别阳痿、早泄、短小、腰膝酸软、尿频尿急等男性问题，重振男人雄风。如果您有男性问题，可以加董奉堂老医师强肾团队微信，运用独家奇方为您悉心调理，保证疗程效果，不让你白花一分冤枉钱。效果好，您就告诉身边的10个人，效果不好，您就告诉身边100个人！");
document.writeln("         ");
document.writeln("        </div>");
document.writeln("<br data-filtered=\'filtered\'>");
document.writeln("");
document.writeln("");
document.writeln("         <div class=\'contact\'>");
document.writeln("			&nbsp;");
document.writeln("		 </div>");
document.writeln("");
document.writeln("        <div class=\'title\'>换个“新老公”，老婆直喊：爽！</div>");
document.writeln("        <img class=\'lazy\' src=\'./images/aa3.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        <div class=\'pt\'>小王今年27岁，是个IT男，工作生活压力大，身体和精力严重透支，夫妻生活3分钟算好的，好不容易“雄起”了，经常会中途疲软，1分钟就射了。有时候和老婆看日本动作片，她一点反应都没有，老婆却会陶醉的说别人怎么那么粗长那么持久，对他的态度也越来越差，说他中看不中用，有时候还跟别的男人打情骂俏，婚姻摇摇欲坠！为了满足老婆，偷着吃了不少补肾药，应付一阵，过后身体像掏空了一样，经常出现头晕眼花，全身无力，真担心废了！两个月前，小王通过一个哥们的介绍，开始用董奉堂老医师的强肾古方进行调理:：</div>");
document.writeln("        <div class=\'sanbu\'>");
document.writeln("            <p><span>当天：</span>腰酸腿软、晚上出虚汗得到缓解；</p>");
document.writeln("            <p><span>三天后：</span>晨勃回来了，而且从早上5点一直硬到7点，有了明显的冲动；</p>");
document.writeln("            <p><span>一周后：</span>小弟弟每天精神抖擞，雄起速度快，意念到，小弟到，收发自如！罢工和快枪手的情况再也没有发生；时间能控制在30分钟左右。老婆开玩笑说用了这个方子像换了个人似的。</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'pt\'>&nbsp;现在坚持了两个月，时间随意控制，更意外的是小弟弟二次发育，一点点增大增长，老婆一只手握都握不住，太意外了！小王骄傲的说：是强肾灸让他真正找到了做男人的感觉，就两个字：霸气！</div>");
document.writeln("        <div class=\'title\'>“面条”变“铁棒”，女人大呼受不了</div>");
document.writeln("        <img class=\'lazy\' src=\'./images/41.jpg\' width=\'100%\' alt=\'\'>");
document.writeln("        <div class=\'pt\'>杭州经营两家公司的温先生，42岁，在当地也算名人，有钱有权。但由于以前忙事业，熬夜应酬，3年前开始，发现自己有些阳痿，夫妻生活质量越来越差，晚上还起夜几次。尤其老婆还不到30岁，欲望强，自己又喂不饱，无法满足，真担心有一天给他戴绿帽子。也曾经用了很多方法，基本没有什么效果。三个月前，加了董奉堂老医师学生的微信经过沟通问诊以后，开始用董奉堂老医师的强肾古方进行调理:</div>");
document.writeln("        <div class=\'sanbu\'>");
document.writeln("            <p><span>3天：</span>爱起夜、尿急的现象大大改善；</p>");
document.writeln("            <p><span>7天以后：</span>一股冲动直往外涌，肾活力立即迸发，大不一样；</p>");
document.writeln("            <p><span>一个月后：</span>疲软不硬、硬而不坚、坚而不久、时间短等现象一扫而光，整个人不仅精神了，而且恢复了活力和精力，老婆十分满意，自已也自豪感暴满。</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'pt\'>到现在已经坚持了三个月了，用他自己的话讲：那种妙不可言的生猛劲，每次都让老婆求饶，好像又回到了18岁，让我自由控制，简直是脱胎换骨！</div>");
document.writeln("");
document.writeln("");
document.writeln("		<div class=\'contact\'>");
document.writeln("		&nbsp;");
document.writeln("		</div>");
document.writeln("");
document.writeln("");
document.writeln("        <div class=\'title\'>3天助勃，7天延时，60天增大增粗</div>");
document.writeln("        <img class=\'lazy\' src=\'./images/top9.jpg\' width=\'100%\' alt=\'\'><br data-filtered=\'filtered\'><br data-filtered=\'filtered\'>");
document.writeln("        <p style=\'display: inline-block;vertical-align: top;padding: 0px 8px;border-top-right-radius: 0.5em;border-bottom-right-radius: 0.5em;color: rgb(255, 255, 255);text-align: center;font-size: 24px;box-sizing: border-box;background-color: rgb(178, 0, 0);\'>助勃</p>");
document.writeln("        <div class=\'neirong\'>短短3天，久违的晨勃回来了，受到刺激后勃起的速度增加10倍以上，可以说一触即动，快速进入状态！</div><br data-filtered=\'filtered\'>");
document.writeln("        <p style=\'display: inline-block;vertical-align: top;padding: 0px 8px;border-top-right-radius: 0.5em;border-bottom-right-radius: 0.5em;color: rgb(255, 255, 255);text-align: center;font-size: 24px;box-sizing: border-box;background-color: rgb(178, 0, 0);\'>延时</p>");
document.writeln("        <div class=\'neirong\'>7天左右，阳痿、早泄一扫而空，时间大大延长，从过去的3分钟到分延长到了20分钟、40分钟，还有哪个女人达不到快乐的巅峰？什么样的女人无法满足、无法征服呢？</div>");
document.writeln("        <p style=\'display: inline-block;vertical-align: top;padding: 0px 8px;border-top-right-radius: 0.5em;border-bottom-right-radius: 0.5em;color: rgb(255, 255, 255);text-align: center;font-size: 24px;box-sizing: border-box;background-color: rgb(178, 0, 0);\'>增大</p>");
document.writeln("        <div class=\'neirong\'>60天男性器官的长度、围度明显增加，平均增长5-7厘米、增粗1-2倍，填满爱人的欲望，爱爱更加深入紧密，100%的完全融合！变大变粗的男性器官不会反弹变小！</div>");
document.writeln("        <div class=\'title\'>巧用董奉堂老医师强肾古方，前后“判若两人””</div>");
document.writeln("        <div style=\'text-align: center;background-color: rgb(178,0,0);color:white;padding: 10px 0;\'>");
document.writeln("            <p>以前软秧子——现在硬将军！</p>");
document.writeln("            <p>以前闪电战——现在持久战！</p>");
document.writeln("            <p>以前等着硬——现在硬着等！</p>");
document.writeln("            <p>以前毛毛虫——现在大巨人！</p>");
document.writeln("            <p>以前虎头蛇尾——现在一爽到底！</p>");
document.writeln("            <p>以前三分钟买单——现在绝不休战！</p>");
document.writeln("        </div>");
document.writeln("        <div class=\'pt\' style=\'text-align: center;color: rgb(178,0,0);\'>**独家秘密武器“董奉堂老医师强肾古方”——让男人充满战斗力，让女人彻底离不开你！**</div>");
document.writeln("        <div class=\'neirong\'>调查显示，30岁以上女性，更加注重男人性能力，硬度、尺度、持久度，是女人对性伴侣是否满意的三个主要标准。但是，仅有18.3%的女性能在这方面得到满足。如果想让你的女人更爱你，想让你的女人更离不开你，那就赶快添加董奉堂老医师的微信号：  <span style=\'color: rgb(87, 69, 221); line-height: 1.6; letter-spacing: 0px; font-size: 16px; font-weight: bold; box-sizing: border-box;\' name=\'gongxifacai\'>");
document.writeln("<script data-filtered=\'filtered\'> document.write(stxlwx);</script>");
document.writeln("</span>  一旦尝试，你会收到意想不到的神奇效果哦！</div>");
document.writeln("        <div style=\'text-align: center;font-weight: bold;font-size: 24px;\'>董奉堂老医师微信朋友圈时时更新康复案例！</div><br data-filtered=\'filtered\'><br data-filtered=\'filtered\'>");
document.writeln("        <div class=\'msg_desc\'>");
document.writeln("            <div class=\'comment\'>");
document.writeln("                <h5>精彩留言</h5>");
document.writeln("                <h1>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/1.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>天助者<em><i class=\'icon\'></i>60</em></span> 男人就怕肾虚...肾虚了啥都不行了");
document.writeln("                            <o>1天前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/aa.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>阿伯<em><i class=\'icon\'></i>28</em></span> 感谢分享，董奉堂老医师挺出名得，网上看过好多介绍他的文章了");
document.writeln("                            <o>1天前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/2.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>闸北老克勒<em><i class=\'icon\'></i>62</em></span> 是不是真的啊？做爱10分钟，女人没高潮，可以看好的吗？");
document.writeln("                            <o>2天前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/3.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>闲云野鹤<em><i class=\'icon\'></i>59</em></span> 如果这个方法有用，我一定给楼主发个大红包，这么些年为了补肾可没少走冤枉路！");
document.writeln("                            <o>2天前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/nn1.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>一叶知秋水<em><i class=\'icon\'></i>112</em></span> 老公调理一个月了，变化很明显，大、粗、硬，时间也很长，享受过高潮的我越来越离不开他了。");
document.writeln("                            <o>5天前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/4.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>风烛人家<em><i class=\'icon\'></i>126</em></span> 我吃过速效的、还有伟哥，当时吃有点儿用，不吃就完全硬不起来，都是激素，对身体伤害太大了。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/5.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>楚天舒<em><i class=\'icon\'></i>93</em></span> 是啊，速效激素类的肯定不能吃啊，我身体本来不太好，有次吃过伟哥，做完以后后背都是虚汗，头发涨，头疼，再也不敢吃了。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/6.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>鈊囚箛島<em><i class=\'icon\'></i>63</em></span> 作为一个快枪手，我一直好奇做半个小时是什么体验");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/nn2.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>叶自飘飘<em><i class=\'icon\'></i>134</em></span> 看到这个我就想起我前男朋友，要是他早点用上这个方法，我们可能也不用分手了吧");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/8.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>真心英雄<em><i class=\'icon\'></i>94</em></span> 怎么买啊？我也好想试试。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                        <p class=\'nomar\'>");
document.writeln("                            <span>作者回复：<em><i class=\'icon\'></i>83</em></span> 兄弟加微信");
document.writeln("                            <span class=\'weixin touchArea\' data-filtered=\'filtered\'><script>document.write(stxlwxs)</script></span>。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/9.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>操的一手好蛋<em><i class=\'icon\'></i>87</em></span> 这么强大，我也要试试");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/10.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>前进铝材<em><i class=\'icon\'></i>98</em></span> 岁月是把杀猪刀，从前迎风尿三丈，如今顺风沾湿鞋，唉。。。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/11.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>92年的中年人<em><i class=\'icon\'></i>111</em></span> 已经加了老医师助理的微信，希望我也能轻松变猛男。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/nn3.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>失落的，痛<em><i class=\'icon\'></i>106</em></span> 各位姐妹要注意了，这个东西千万不要给你的男人用了，除非你有好的体力天天把他榨干，否则很有可能分分钟给你来个彩色的帽子。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/12.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>岁月沉淀<em><i class=\'icon\'></i>78</em></span> 最可怕的是年龄，比年龄更可怕的是一颗不服老的心！我也要强壮！");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/timg7.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>米兰脑残粉<em><i class=\'icon\'></i>73</em></span> 果断添加！！！");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/timg.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>此情此景，吟诗一首<em><i class=\'icon\'></i>66</em></span> 接下来就是见证奇迹的时刻。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/nn5.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>茜茜<em><i class=\'icon\'></i>95</em></span> 真是厉害，我老公原来爱爱时间只能做10分钟不到，用了2个月不到，爱爱时间最少30分钟，最主要他小弟弟比原来大了，硬了，热热的，能把我下面撑的满满的，并且顶到最里面，再加上30分钟的刺激，我真是爱死他了。");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/timg9.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>1个狠oK的男人<em><i class=\'icon\'></i>121</em></span> 试过好多方法了，都不管用，纠结，算了先添加试试吧！");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                    <div>");
document.writeln("                        <img class=\'lazy tx\' src=\'./images/timg4.jpg\'>");
document.writeln("                        <p>");
document.writeln("                            <span>董奉堂酒幽梦<em><i class=\'icon\'></i>102</em></span> 挺好的，在别的地方也看到了这篇，效果应该挺不错的 哎......");
document.writeln("                            <o>1小时前</o>");
document.writeln("                        </p>");
document.writeln("                    </div>");
document.writeln("                </h1>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div><br><br><br></div>");
document.writeln("");
document.writeln("<div class=\'qwe\'>");
document.writeln("<div class=\'floatcontact\' onclick=\'popup()\'>");
document.writeln("<span style=\'padding-right: 9px;\'>");
document.writeln("<img class=\'wechatsvg\' src=\'./images/wechat.png\'></span>");
document.writeln("<span class=\'am-container\'>点击加老医师微信教你补肾壮阳秘法</span>");
document.writeln("</div>");
document.writeln("<div id=\'wechatBox\' onclick=\'closeP()\'>");
document.writeln("</div>");
document.writeln("<div id=\'wechat\'>");
document.writeln("<div class=\'contact popmol\'>");
document.writeln("<div class=\'contactstyle pc\'>");
document.writeln("&nbsp;");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\'sidefuck\'><div class=\'sidecontact\'><p><img src=\'./images/shitu.jpg\' width=\'100%\'></p><p style=\'line-height: 1.75;\'>如果你想治疗阳痿、早射，补肾、壮阳，增大、增粗20分钟。<span class=\'abcqw ss\'>立即咨询董奉堂老医师</span>，教你如何针对性调补，再试试老医师亲手炮制的秘方，一定有意想不到的惊喜哦。</p><p style=\'text-align:center;\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("</span></p></div></div>");