document.writeln("  <meta name=\'viewport\' content=\'width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0\' /> ");
document.writeln("  <meta name=\'apple-mobile-web-app-capable\' content=\'yes\' /> ");
document.writeln("  <meta name=\'apple-mobile-web-app-status-bar-style\' content=\'black\' /> ");
document.writeln("  <meta name=\'format-detection\' content=\'telephone=no\' /> ");
document.writeln("<meta http-equiv=\'X-UA-Compatible\' content=\'IE=edge,chrome=1\' /> ");
document.writeln("  <title>[360安全认证]凤凰男性专题</title> ");
document.writeln(" <head>");
document.writeln("  <link media=\"all\" href=\"./images/index.css\" type=\"text/css\" rel=\"stylesheet\" />");
document.writeln("<script type=\"text/javascript\" src=\"./images/wx.js\"></script>");
document.writeln("<link rel=\"stylesheet\" href=\"./images/contact.css\"  type=\"text/css\">");
document.writeln("<script src=\"./images/jquery.min.js\"></script>");
document.writeln("<script src=\"./images/lazyload.min.js\"></script>");
document.writeln("<script src=\"./images/clipboard.min.js\"></script>");
document.writeln(" </head>");
document.writeln(" <body style=\"user-select: none;\" >");
document.writeln("  <div class=\"kuang\" id=\"abccba\"> ");
document.writeln("   <div class=\"con\" deep=\"1\"> ");
document.writeln("    <p style=\"text-align: center; background-color: rgb(190, 0, 0); font-weight: bold; text-indent: 0em; color: rgb(255, 255, 255); letter-spacing: 1px; font-size: 19px;\">六旬老人没人敢嫁，原来是那方面太强！</p> ");
document.writeln("    <div style=\"font-weight: bold;line-height: 8px;margin-left: -25px;font-size: 14px;\"> ");
document.writeln("     <p>2018年09月02日 08:01:43</p> ");
document.writeln("     <p> <span class=\"ss02\">来源：</span> <span itemprop=\"name\" class=\"ss03\"> <a href=\"javascript:;\" itemprop=\"isBasedOnUrl\" target=\"_blank\" ref=\"nofollow\">凤凰健康</a></span> </p> ");
document.writeln("    </div> ");
document.writeln("    <p class=\"jij\">近日，家住在湖南省的老蒋心情可不太好，当了半辈子模范代表的他，竟因为涉黄被请进了派出所！作为小区里公认正直和蔼的老前辈，老蒋一直很受社区居民的尊敬。但谁也没有想到，居然在他身上发生了这种事！但其中的缘由到底又是什么呢？日前，社会新闻的记者联系了相关新闻事件人，一个神奇的秘密由此被揭开......</p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/1.jpg\" width=\"96%\" src=\"./images/1.jpg\" /> ");
document.writeln("    <p class=\"jij\">据了解，老蒋在被抓获时，女子已经明显脱力，甚至无法自行站立，而此前老蒋却仿佛浑然不知，直到警察破门而入时，才惊慌失措的被逮个正着。令人唏嘘的是，该女子竟是刚毕业的研究生，只为快速赚钱，才入了这行，可万万没想到，初次就遇到了这种事！</p> ");
document.writeln("    <p class=\"jij\"> 为了一探究竟，记者找到以前跟老蒋生活过的几个女人，谁知得到的答案是同一个，就是老蒋 下面太大，每夜要做六、七次，一次都要四十分钟以上，让记者感到震惊，老蒋67岁了，身体要比年轻人都好，于是记者问老蒋，老蒋回答自己以前肾虚，偶然听到朋友说一位老中医祖传下来一副专门补肾养睾秘方。回家后，老蒋迫不及待的开始试验药方效果，不到一周之后，不但精神十足，连多年没有的晨勃反应都出现 了！而且突然发现比以前大了不少，就在近一个礼拜，老蒋逐渐感觉越来越有冲动，不但容易出现生理反应，而且经常持续一个多小时不觉疲倦，就连上个老伴都是受不了老蒋的“大家伙”被折腾去世的。这次就遇到了这种事！ </p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/2.jpg\" width=\"96%\" src=\"./images/2.jpg\" /> ");
document.writeln("    <p class=\"jij\">记者怀疑这配方该不会是什么催情药吧？几经周折结拿到配方之后，经过分析后才发现，这个补肾养睾秘方不但能够补肾填精，助兴壮阳，还能调理虚损，提高免疫等功效，且药性极强却又中正平和，不但没有副作用，反而对人身体大有益处。</p> ");
document.writeln("   ");
document.writeln("	");
document.writeln("	");
document.writeln("	");
document.writeln("	<div class=\"contact\"> </div> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <p style=\"text-align: center; background-color: rgb(190, 0, 0); font-weight: bold; text-indent: 0em; color: rgb(255, 255, 255); letter-spacing: 1px; font-size: 24px;\">神秘老中医究竟是何来历？</p> ");
document.writeln("    <p class=\"jij\">老中医家原本住在雷公山坳中的一个小山村，其常氏家族作为世代中医家族，数百年来一直给附近十里八乡的百姓问诊。在清康熙年间，祖辈更是当时皇家御医。目前，<span style=\"color: white;background-color: red;\">老中医是特聘专家。</span>为了捍卫“原版中医”传承中医药学术思想，最近老中医首度公开了清宫御用奇方，老为广大男性朋友提供有效的治疗，不求名，不为利，只为帮助男人告别阳痿、早泄、短小、腰膝酸软、尿频尿急等男性问题，重振男人雄风。</p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/3.jpg\" width=\"96%\" src=\"./images/3.jpg\" /> ");
document.writeln("    <p style=\"text-align: center;\">（老中医）</p> ");
document.writeln("    <p style=\"text-align: center; background-color: rgb(190, 0, 0); font-weight: bold; text-indent: 0em; color: rgb(255, 255, 255); letter-spacing: 1px; font-size: 24px;\">老中医百年强肾方的渊源-清宫秘传</p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/4.jpg\" width=\"96%\" src=\"./images/4.jpg\" /> ");
document.writeln("    <p style=\"text-align: center;\">（康熙夜驭30妃嫔，而且“九妃连珠”，足见其男性能力之强大）</p> ");
document.writeln("    <p class=\"jij\">“我家祖辈自康熙帝开始，就是宫廷御医。康熙一夜临幸30妃，靠的就是这个独门方法。秘方传到现在，我不断加以改进，组方几乎完美，解决肾虚，所向披靡， 战无不胜！能给你带来立竿见影的威猛效果！不管你是早泄、阳痿、不够坚挺，或者尺寸短小，等男性功能障碍。都能给你彻彻底底的改善，让你站在人生性福的高峰！” </p> ");
document.writeln("    <p class=\"jij\">“补肾养睾秘方”来源于古方改良，经过老中医多次改良调制之后，效果是原来的数倍，已经从无数患者的身上得到了实践和证实，里面的每份中药材都提取了它的核心价值成分，药效得到了很大的提升！3天就能见效，7天就有明显改善，有的人一周后男性功能提高，有的人一个月男科问题彻底解决。这么说吧，到目前为止，老中医还没有遇到一个对效果不满意的！</p> ");
document.writeln("    <p class=\"\" style=\"margin-top: 1em; padding: 5px 10px; white-space: normal; font-family: 微软雅黑; line-height: 1.75;     display: inline; color: white; background-color: rgb(190, 2, 2); font-weight: bolder; border-radius: 10px; font-size: 18px;\">老中医郑重声明</p> ");
document.writeln("    <p class=\"jij\">“我专补男性的肾，只要你亏虚，保管你七天见效！</p> ");
document.writeln("    <p class=\"jij\">第一个，补肾快！第二个，补肾持久！第三个，补肾全面！我这个宫廷秘方，10分钟就管事！不但快，而且很持久。关键这个持久，一点不透支你的身体，是根部的动力，在起作用。</p> ");
document.writeln("    <p class=\"jij\">再一个，肾虚是一个非常广泛的疾病范畴，除了夫妻生活，还会出现很多糟糕的疾病。用我的方法，不仅补了肾，顺带把肾虚引起很多的病，比如尿频尿急，白发脱发，失眠健忘，腰腿酸软乏力……这些病也能得到很彻底的治疗。这叫全面补肾。</p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/5.jpg\" width=\"96%\" src=\"./images/5.jpg\" /> ");
document.writeln("    <p style=\"text-align: center;\">（老中医为患者准备特制外用膏）</p> ");
document.writeln("    <p class=\"jij\">所以我告诉大家一句话，中国人补肾，还是得用针对中国人的方法！具体可长按下方二维码添加我微信咨询。有把握我就为你开方，无把握你也不受损失。</p> ");
document.writeln("");
document.writeln("");
document.writeln("    <div class=\"contact\">  </div> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <p style=\"width: 100%;height: 0px;\"></p> ");
document.writeln("    <!-- <img class=\"lazy\" data-original=\"index_files/28.png\" center;=\"\" align=\"\"> --> ");
document.writeln("    <p class=\"jij\"><span style=\"background-color: rgb(179, 0, 0); color: rgb(255, 255, 255); padding: 3px 15px; border-radius: 8px;\">助勃</span></p> ");
document.writeln("    <p class=\"jij\" style=\"text-indent: 3em;\">短短3天，久违的晨勃回来了，受到刺激后勃起的速度增加10倍以上，可以说一触即动，快速进入状态！</p> ");
document.writeln("    <p class=\"jij\"><span style=\"background-color: rgb(179, 0, 0); color: rgb(255, 255, 255); padding: 3px 15px; border-radius: 8px;\">延时</span></p> ");
document.writeln("    <p class=\"jij\" style=\"text-indent: 3em;\">7天左右，阳痿、早泄一扫而空，时间大大延长，从过去的3分钟到分延长到了20分钟、40分钟，还有哪个女人达不到快乐的巅峰？什么样的女人无法满足、无法征服呢？</p> ");
document.writeln("    <p class=\"jij\"><span style=\"background-color: rgb(179, 0, 0); color: rgb(255, 255, 255); padding: 3px 15px; border-radius: 8px;\">增大</span></p> ");
document.writeln("    <p class=\"jij\" style=\"text-indent: 3em;\">60天男性器官的长度、围度明显增加，平均增长3-5厘米、增粗1-2倍，填满爱人的欲望，爱爱更加深入紧密，100%的完全融合！</p> ");
document.writeln("    <p class=\"jij\" style=\"text-align: center; text-indent: 0em;\"><span style=\"background-color: rgb(179, 0, 0); color: rgb(255, 255, 255); padding: 3px 15px; border-radius: 8px;\">巧用补肾养睾秘方，前后“判若两人”</span></p> ");
document.writeln("    <p class=\"jij\" style=\"border: 3px solid rgb(190, 0, 0); letter-spacing: 1px; padding-top: 10px; padding-bottom: 10px; padding-left: 15px; text-indent: 0em; margin-top: -20px; text-align: center;\"> 以前软秧子——现在硬将军！ <br data-filtered=\"filtered\" />以前闪电战——现在持久战！ <br data-filtered=\"filtered\" />以前等着硬——现在硬着等！ <br data-filtered=\"filtered\" />以前毛毛虫——现在大巨人！ <br data-filtered=\"filtered\" />以前虎头蛇尾——现在一爽到底！ <br data-filtered=\"filtered\" />以前1分钟买单——现在40分钟绝不休战！ </p> ");
document.writeln("    <p class=\"jij\">★★★独家秘密武器“补肾养睾秘方”——让男人充满战斗力，让女人彻底离不开你！★★★</p> ");
document.writeln("    <p class=\"jij\">如果想让你的女人更爱你，想让你的女人更离不开你，那就赶快添加老中医微信，一旦尝试，你会收到意想不到的神奇效果哦！</p> ");
document.writeln("    <p class=\"jij\">女人的满足，男人的责任！补肾养睾秘方让不举的男人重振雄威，让早泄的男人持久不射，让成功的男人更强硬，让能力重回年轻，力大无穷！一硬到底，持久不泄，超爽快感！也让女人小溪潺潺，燕语莺声，娇喘连连。男人强，女人爽，生活和谐，性福满满！</p> ");
document.writeln("    <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/6.jpg\" src=\"./images/6.jpg\" /> ");
document.writeln("    <p></p> ");
document.writeln("    <img class=\"lazy\" data-original=\"index_files/bgx.jpg\" style=\"margin-top: 0px;\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC\" /> ");
document.writeln("    <div style=\"border-top: 2px none;\"> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; margin-bottom: -15px; font-size: 22px; text-indent: 0em;\"><span>我就要这种粗大持久、高潮不断</span></p> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; font-size: 22px; text-indent: 0em;\"><span>欲仙欲死的感觉</span></p> ");
document.writeln("     <p class=\"jij\"><span style=\"font-weight: normal; color: rgb(254, 2, 2);\">老公那里比较小，每次抽插一点感觉都没有，还不如我自己解决，深夜来临的时候，我都会想我前男友</span>，想他那强悍有力的小弟弟，每次都可以让我高潮不断，一个晚上可以要五六次。后来老公用了补肾养睾秘方后，感觉就不一样了，<span style=\"font-weight: normal; background-color: rgb(190, 0, 0); color: rgb(255, 255, 255);\">开始用3天，竟然马上有了感觉，欲火焚身，下体发热，发胀，一定要把我就地正法。每次把我压在身下浑身是劲，搞得我高潮不断，呻吟连连，水流不止，每天基本都搞40分钟以上，爽到我欲仙欲死！</span></p> ");
document.writeln("     <!--<img class=\"lazy\" style=\"margin-top: 0px;\" data-original=\"./index_files/26a.jpg\" />--> ");
document.writeln("     <p class=\"jij\">两个月后的一天，我在看电视，他刚洗完澡，因为坚持使用秘方，下面胀得很大，比平时大了一倍，突然把我按倒在沙发上，那略带胡茬的嘴在我的身上吻着，一个翻身骑到我的身上，支开我的双腿一个挺身，粗野的扯下我的内裤毫不客气的插入我下面。</p> ");
document.writeln("     <p class=\"jij\"><span style=\"font-weight: normal; background-color: rgb(190, 0, 0); color: rgb(255, 255, 255);\">我 心里一惊，这还是他么？粗了这么多？“疼”，我不自觉的叫出声了。老公并不理会我，继续着他的动作，我慢慢地放松了，从脚趾尖开始，觉得有一丝丝的暖意， 然后顺着筋络，一直延伸到大腿根，紧接着，私处内不停的抽搐，大脑放空，高潮持续不断，第一次体会到了那种水乳交融的感觉，觉得一瞬间欲仙欲死，沙发湿了 一大片，一炮爽到九宵云外，这次足足做了90分钟。</span></p> ");
document.writeln("    </div> ");
document.writeln("    <img class=\"lazy\" data-original=\"index_files/bgx.jpg\" style=\"margin-top: 0px;\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC\" /> ");
document.writeln("    <div style=\"border-top: 2px none;\"> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; margin-bottom: -15px; font-size: 22px; text-indent: 0em;\"><span>她想要的高.潮，你给不了</span></p> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; font-size: 22px; text-indent: 0em;\"><span>那是最大的杯具！</span></p> ");
document.writeln("     <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/7.jpg\" src=\"./images/7.jpg\" /> ");
document.writeln("     <p class=\"jij\">这两年身体一天不如一天，尤其是在床上越来越不行，<span style=\"font-weight: normal; color: rgb(254, 2, 2);\">每次都力不从心，尤其是勃起后硬度不够，有时候硬塞都塞不进去，做也是1、2分钟了事，面对老婆那渴望的目光，真害怕哪天隔壁老王趁虚而入。</span>为了医好我得病，吃了不少药，花了不少钱，可怜的是能力一点没有改善。</p> ");
document.writeln("     <p class=\"jij\">就在我快要奔溃的时候，朋友向我推荐了老中医，<span style=\"font-weight: normal; background-color: rgb(190, 0, 0); color: rgb(255, 255, 255);\">我坚持服用了一个月，没想到效果很是明显，小弟比以前增长了2厘米，有了坠吊感，勃起后硬的像钢筋，重新找到了年轻时的雄风。那一夜，足足有2个多小时，老婆一直在尖叫，我也爽到了极点</span>，尽情释放了我的激情。</p> ");
document.writeln("     <img class=\"lazy\" data-original=\"static/picture/8.jpg\" align=\"middle\" src=\"./images/8.jpg\" style=\"display: block;\" /> ");
document.writeln("     <p style=\"font-size: 18px; text-align: center;\"><span style=\"font-weight: normal; background-color: rgb(190, 0, 0); color: rgb(255, 255, 255); font-size: 18px;\">(现在老婆天天爬到我身上缠着我想要)</span></p> ");
document.writeln("    </div> ");
document.writeln("    <img class=\"lazy\" data-original=\"index_files/bgx.jpg\" style=\"margin-top: 0px;\" src=\"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC\" /> ");
document.writeln("    <div style=\"border: 2px none;\"> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; margin-bottom: -15px; font-size: 22px; text-indent: 0em;\"><span>娶了小20岁的女人</span></p> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; font-size: 22px; text-indent: 0em;\"><span>一样让她欲仙欲死</span></p> ");
document.writeln("     <img class=\"lazy\" style=\"margin-top: 0px; display: block;\" data-original=\"static/picture/9.jpg\" src=\"./images/9.jpg\" /> ");
document.writeln("     <p class=\"jij\">去年和一个比我小22岁的女人结了婚，老兄弟都笑话我“在床上要出人命的”他们不知道的是，<span style=\"font-weight: normal; color: rgb(254, 2, 2);\">我这几年每年都用补肾养睾秘方调理身体，所以性能力一直都非常旺盛，基本每次都能让小妻子尖叫高潮，其实以前我的能力一直都不强，年过四十后更是一直软塌塌的，不管多漂亮的小姑娘同事，那活也硬不起来。</span></p> ");
document.writeln("     <p class=\"jij\">直到客户介绍补肾养睾秘方给我，结果太让我兴奋了，那种坚硬、持久的感觉就像回到了20岁，<span style=\"font-weight: normal; background-color: rgb(190, 0, 0); color: rgb(255, 255, 255);\">连续吃了几个月，下面竟然隐隐大了5公分，狂猛持久加上这十几年的技术，不管什么类型的女人总能轻易让她们高潮不断，现在每次和小妻子做爱都能一战到底，连续1小时，直达她欲仙欲死，连连求饶才罢休。</span>这才是真正的生活，她现在对我简直是言听计从，黏人的不得了，现在我们的感情更好了，真是从内心里感谢老中医！</p> ");
document.writeln("    </div> ");
document.writeln("    <img class=\"lazy\" data-original=\"static/picture/10.jpg\" align=\"middle\" src=\"./images/10.jpg\" style=\"display: block;\" /> ");
document.writeln("    <p class=\"jij\">想成为真正的男人，让她狂叫不停，爽到极点吗？那赶紧加老中医的微信，在线咨询调理方案，让你重振男人雄风！</p> ");
document.writeln("    ");
document.writeln("	");
document.writeln("	<div class=\"contact\">  </div> ");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <div style=\"background-color: rgb(240, 246, 198); width: 100%;\"> ");
document.writeln("     <p class=\"jij\" style=\"text-align: center; text-indent: 0em;\"><span style=\"background-color: rgb(240, 246, 198); font-weight: bold; text-indent: 0em; color: rgb(190, 0, 0); letter-spacing: 1px; text-align: center; font-size: 22.5px;\" class=\"ewmNum wxhs1\">文章仅保留10分钟<br data-filtered=\"filtered\" />请先添加老中医微信防止失联</span></p> ");
document.writeln("    </div> ");
document.writeln("    <img class=\"lazy\" data-original=\"static/picture/11.jpg\" style=\"margin-bottom: 5px; margin-top: 5px; display: block;\" src=\"./images/11.jpg\" /> ");
document.writeln("    <div class=\"hidden-xs\" style=\"z-index: 2147483647; position: fixed !important; right: 10px; top: 200px;\" id=\"isEwm\" data-filtered=\"filtered\"> ");
document.writeln("    </div> ");
document.writeln("    <div class=\"pinglun\" style=\"margin-top: 20px;\"> ");
document.writeln("     <div class=\"zan\">");
document.writeln("      快乐的小布丁、花虎、风吹落叶等6547位好友评论");
document.writeln("     </div> ");
document.writeln("     <ul id=\"j_newslist\"> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/1.jpg\" src=\"./images/1(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           快乐的小布丁");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">1</em>楼 1天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我阳痿已经3年了，找好多老中医看过，吃了不少产品，都不管用，你这个管用吗？ ");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\">");
document.writeln("        <span>楼主：</span>你的病症时间比较久了，建议不要乱服别的产品，你可以加老中医微信，详细聊一下！");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\">");
document.writeln("        <span>花猫王：</span>这个是真的，我前两个月用过补肾养睾秘方，现在每次都在40分钟左右，做得超爽！");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">5543</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/2.jpg\" src=\"./images/2(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           花虎");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">2</em>楼 1天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我早泄问题十几年了，去年在朋友介绍下，介绍了补肾养睾秘方给我，调理半年好了，现在基本每次都能做30分钟以上，太感谢老中医了。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">572</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/3.jpg\" src=\"./images/3(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           风吹落叶");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">3</em>楼 3天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我每次不到3分钟就射了，用这个可以方子可以解决吗？有没有和我一样症状的朋友调理好过？ ");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\"> ");
document.writeln("        <span>绿皮车：</span>亲这种症状很典型呢，我和你一样，坚持吃补肾养睾秘方，现在慢慢的时间越来越长，我现在30分，希望能帮到你。 ");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\"> ");
document.writeln("        <span>风吹落叶：</span>谢谢，请问老中医的微信二维码是这个吗？ ");
document.writeln("        <script> document.write(\'<img class=\"qrcode limas weixinpic\" />\' )</script>");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\"> ");
document.writeln("        <span>绿皮车：</span>是的，是这个二维码，赶紧长按识别添加吧，别耽误了！ ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">8710</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/4.jpg\" src=\"./images/4(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           风景B");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">4</em>楼 3天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我从小就手婬，现在结婚了，感觉力不从心，特别软，好不容易做一次，才3分钟！ ");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\">");
document.writeln("        <span>楼主：</span>你的问题很常见，补肾养睾秘方调理好了无数你这样的朋友，我非常有信心。");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">687</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/5.jpg\" src=\"./images/5(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           沙漠的约定");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">5</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我已经50多岁了，阳痿早泄十多年了，吃这个还管用吗。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">782</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/6.jpg\" src=\"./images/6(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           小埋");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">6</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我今年45岁，想生二胎，但是我阳痿已经5年了，一个月最多和老婆亲热一次，根本没机会怀上。 ");
document.writeln("       </div> ");
document.writeln("       <div class=\"hf\" style=\"font-size: 16px;\">");
document.writeln("        <span>楼主：</span>你的想法我理解，你目前的症状吃补肾养睾秘方3个月，保证你一周两次没问题！");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">782</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/7.jpg\" src=\"./images/7(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           轻松熊");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">7</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我是上个月开始用你的方子的，现在感觉硬了许多，每次时间比以前增加了有10多分钟吧，强烈推荐。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">147</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/8.jpg\" src=\"./images/8(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           月光");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">8</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         我去年用过，吃了3个月，由于出国一年，就断开了，效果是非常好的，我老婆是外国人，现在每次她都受不了我。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">183</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/9.jpg\" src=\"./images/9(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           蜂蜜草");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">9</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         这个产品真心不错，就在我们当地，我们当地的店里都进他们的货在卖，火的很。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">735</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/9.jpg\" src=\"./images/9(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           向往自由");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">10</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("         能告诉我地址吗，我可以自己过去拿吗，谢谢。 ");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">583</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("      <li> ");
document.writeln("       <dl> ");
document.writeln("        <dt> ");
document.writeln("         <img class=\"lazy\" data-original=\"static/picture/tx/10.jpg\" src=\"./images/10(1).jpg\" style=\"display: block;\" /> ");
document.writeln("        </dt> ");
document.writeln("        <dd> ");
document.writeln("         <div>");
document.writeln("           六月飞雪");
document.writeln("          <br data-filtered=\"filtered\" /> ");
document.writeln("          <a style=\"color:#555555; font-size:17px; text-decoration:none; line-height:28px;\">第<em id=\"locen\">11</em>楼 5天前&nbsp;&nbsp;&nbsp;<span>热评</span></a> ");
document.writeln("         </div> ");
document.writeln("        </dd> ");
document.writeln("       </dl> ");
document.writeln("       <div class=\"pl\" style=\"font-size: 16px;\">");
document.writeln("        我朋友吃过你们家的配方，现在已经换了3个女朋友了，听说是他性欲太强了，女朋友受不了。");
document.writeln("       </div> <span class=\"cmnt_op\"> <a data-sudaclick=\"comment2_4\" href=\"javascript:void(0);\" title=\"赞\" class=\"good j_favor_single\">106</a> <a href=\"javascript:void(0);\" title=\"评论\" class=\"cmntico j_cmnt_single\" data-sudaclick=\"comment1_4\"></a> </span> </li> ");
document.writeln("     </ul> ");
document.writeln("    </div> ");
document.writeln("   </div> ");
document.writeln("   <div style=\"font-size: 14px; color: rgb(139, 138, 137); padding-bottom: 38px; text-align: center;\"> ");
document.writeln("    <div style=\"text-align:center;\">");
document.writeln("     @老医师健康管理团队");
document.writeln("    </div> ");
document.writeln("   </div> ");
document.writeln("  </div> ");
document.writeln("");
document.writeln("");
document.writeln(" ");
document.writeln("<div class=\"qwe\">");
document.writeln("<div class=\"floatcontact\" onclick=\"popup()\">");
document.writeln("<span style=\"padding-right: 9px;\">");
document.writeln("<img class=\"wechatsvg\" src=\"./images/wechat.png\"></span>");
document.writeln("<span class=\"am-container\">点击加老医师微信教你补肾壮阳秘法</span>");
document.writeln("</div>");
document.writeln("<div id=\"wechatBox\" onclick=\"closeP()\">");
document.writeln("</div>");
document.writeln("<div id=\"wechat\">");
document.writeln("<div class=\"contact popmol\">");
document.writeln("<div class=\"contactstyle pc\">");
document.writeln("&nbsp;");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("</div>");
document.writeln("<div class=\"sidefuck\"><div class=\"sidecontact\"><p><img src=\"./images/shitu.jpg\" width=\"100%\"></p><p style=\"line-height: 1.75;\">如果你想治疗阳痿、早射，补肾、壮阳，增大、增粗20分钟。<span class=\"abcqw ss\">立即咨询秦老医师</span>，教你如何针对性调补，再试试老医师亲手炮制的秘方，一定有意想不到的惊喜哦。</p><p style=\"text-align:center;\">");
document.writeln("");
document.writeln(" ");
document.writeln("</span></div></div>");